# Generated by Django 3.2.8 on 2021-10-12 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_profile_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('time', models.DateTimeField(default=datetime.datetime.now, primary_key=True, serialize=False)),
                ('psi', models.FloatField()),
                ('ledState', models.BooleanField()),
                ('solenoidState', models.BooleanField()),
                ('pumpState', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.DecimalField(blank=True, decimal_places=16, default=0.5, max_digits=22, null=True)),
                ('duty', models.DecimalField(blank=True, decimal_places=16, default=0.022, max_digits=22, null=True)),
                ('ledState', models.BooleanField(default=False)),
                ('pressureMax', models.DecimalField(blank=True, decimal_places=16, default=70, max_digits=22, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
