# Generated by Django 3.2.8 on 2021-10-14 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211014_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='bpm',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.5, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='duty',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.022, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='pressureMax',
            field=models.IntegerField(blank=True, default=70, null=True, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(10)]),
        ),
    ]
