# Generated by Django 3.2.8 on 2021-10-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211014_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='device',
            field=models.ForeignKey(default='954f33b2-096b-4000-aae7-35dcdc0b28b4', on_delete=django.db.models.deletion.CASCADE, to='core.device'),
            preserve_default=False,
        ),
    ]
