# Generated by Django 3.2.8 on 2021-10-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sample_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='deviceconfig',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.device'),
        ),
    ]
