# Generated by Django 3.2.8 on 2021-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211019_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='ledState',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='pumpState',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='solenoidState',
            field=models.IntegerField(),
        ),
    ]
